language: python

matrix:
  include:
    - python: "2.7"
      env: DJANGO=1.11 COVERAGE=YES
    - python: "3.4"
      env: DJANGO=1.11
    - python: "3.5"
      env: DJANGO=1.11
    - python: "3.6"
      env: DJANGO=1.11 

    - python: "3.4"
      env: DJANGO=2.0 
    - python: "3.5"
      env: DJANGO=2.0
    - python: "3.6"
      env: DJANGO=2.0 COVERAGE=YES FLAKE8=YES

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils

install:
  - if [[ $DJANGO ]]; then
        pip install "django>=$DJANGO,<=$DJANGO.99";
        pip install mock sh;
        pip install -e .;
    fi;
  - if [[ $COVERAGE == "YES" ]]; then pip install coveralls; fi;
  - if [[ $FLAKE8 == "YES" ]]; then pip install flake8; fi;

script:
  - if [[ $DJANGO ]]; then
        if [[ $COVERAGE != "YES" ]]; then
            make test;
        else
            make coverage;
        fi;
    fi;
  - if [[ $FLAKE8 == "YES" ]]; then make flake8; fi;

after_success:
  - if [[ $COVERAGE == "YES" ]]; then coveralls; fi;
