language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.3.7
    - python: 3.3
      env: DJANGO=1.4.5
install:
  - pip install django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  # run 2to3 for Python 3.3
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then 2to3 -w -n --no-diffs . 2>&1 | tail -n 2; fi"
script: python tests.py
