language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3.5
  - DJANGO=1.4.3
  - DJANGO=https://github.com/django/django/archive/1.5b2.zip
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors
matrix:
  exclude:
    - python: "2.5"
      env: DJANGO=https://github.com/django/django/archive/1.5b2.zip
script: python tests.py
